### PR TITLE
Fetch also supports Mac OS X

### PR DESCRIPTION
**Pull request by dylanaraps**
The script also supports Windows with Cygwin as does Screenfetch but I'm not sure if that counts as Windows support to you. If it does then I'll edit the PR.

Thanks for the site, it's great!

### CODE REVIEW

**Comment by TheReverend403** [comment]
Thanks!

**Comment by dylanaraps** [comment]
No problem! 

Fetch and Screenfetch both support Windows with Cygwin, how do you feel about adding them both to the Windows section of System Info?

**Comment by TheReverend403** [comment]
I don't really consider cygwin as Windows support. If I did, 90% of this list would also be under Windows.

**Comment by dylanaraps** [comment]
Fair enough!

**Pull request merged**
